import { createContext, useContext, useState } from 'react';

export const translations = {
  en: {
    // ── Employee ──
    employeePortal:       "Employee Portal",
    dashboard:            "Dashboard",
    leaveRequest:         "Leave Request",
    attendanceCorrection: "Attendance Correction",
    reports:              "Reports",
    settings:             "Settings",
    logout:               "Logout",
    employee:             "EMPLOYEE",
    // ── Admin ──
    adminPortal:          "Admin Portal",
    staffDirectory:       "Staff Directory",
    leaveApproval:        "Leave Approval",
    attendanceApproval:   "Attendance Approval",
    auditLogs:            "Audit Logs",
    // ── Settings ──
    appearance:               "Appearance",
    chooseTheme:              "Choose your preferred interface theme.",
    light:                    "Light",
    dark:                     "Dark",
    language:                 "Language",
    selectLanguage:           "Select your preferred language.",
    notificationPreferences:  "Notification Preferences",
    manageNotifications:      "Manage what notifications you receive.",
    attendanceAlerts:         "Attendance Alerts",
    attendanceAlertsDesc:     "Get notified about daily attendance status",
    leaveUpdates:             "Leave Request Updates",
    leaveUpdatesDesc:         "Updates when your leave is approved or rejected",
    correctionStatus:         "Correction Request Status",
    correctionStatusDesc:     "Updates on your attendance correction requests",
    emailNotifications:       "Email Notifications",
    emailNotificationsDesc:   "Receive notifications via email",
    editProfile:              "Edit Profile",
    updatePersonal:           "Update your personal information.",
    fullName:                 "Full Name",
    phoneNumber:              "Phone Number",
    department:               "Department",
    designation:              "Designation",
    address:                  "Address",
    saveProfile:              "Save Profile",
    profileUpdated:           "Profile updated successfully!",
    changePassword:           "Change Password",
    updatePassword:           "Update your account password.",
    currentPassword:          "Current Password",
    newPassword:              "New Password",
    confirmPassword:          "Confirm New Password",
    updatePasswordBtn:        "Update Password",
    updating:                 "Updating...",
    passwordChanged:          "Password changed successfully!",
    passwordMismatch:         "New passwords do not match.",
    passwordTooShort:         "Password must be at least 6 characters.",
    networkError:             "Network error. Please try again.",
  },

  ta: {
    // ── Employee ──
    employeePortal:       "ஊழியர் போர்டல்",
    dashboard:            "டாஷ்போர்டு",
    leaveRequest:         "விடுப்பு கோரிக்கை",
    attendanceCorrection: "வருகை திருத்தம்",
    reports:              "அறிக்கைகள்",
    settings:             "அமைப்புகள்",
    logout:               "வெளியேறு",
    employee:             "ஊழியர்",
    // ── Admin ──
    adminPortal:          "நிர்வாக போர்டல்",
    staffDirectory:       "பணியாளர் அட்டவணை",
    leaveApproval:        "விடுப்பு அனுமதி",
    attendanceApproval:   "வருகை அனுமதி",
    auditLogs:            "தணிக்கை பதிவுகள்",
    // ── Settings ──
    appearance:               "தோற்றம்",
    chooseTheme:              "உங்கள் விருப்பமான தீமை தேர்ந்தெடுக்கவும்.",
    light:                    "வெளிர்",
    dark:                     "இருண்ட",
    language:                 "மொழி",
    selectLanguage:           "உங்கள் விருப்பமான மொழியை தேர்ந்தெடுக்கவும்.",
    notificationPreferences:  "அறிவிப்பு விருப்பங்கள்",
    manageNotifications:      "நீங்கள் பெறும் அறிவிப்புகளை நிர்வகிக்கவும்.",
    attendanceAlerts:         "வருகை எச்சரிக்கைகள்",
    attendanceAlertsDesc:     "தினசரி வருகை நிலை பற்றி அறிவிப்பு பெறுக",
    leaveUpdates:             "விடுப்பு கோரிக்கை புதுப்பிப்புகள்",
    leaveUpdatesDesc:         "உங்கள் விடுப்பு அனுமதிக்கப்பட்டது அல்லது நிராகரிக்கப்பட்டது",
    correctionStatus:         "திருத்த கோரிக்கை நிலை",
    correctionStatusDesc:     "உங்கள் வருகை திருத்த கோரிக்கைகளின் புதுப்பிப்புகள்",
    emailNotifications:       "மின்னஞ்சல் அறிவிப்புகள்",
    emailNotificationsDesc:   "மின்னஞ்சல் மூலம் அறிவிப்புகளைப் பெறுக",
    editProfile:              "சுயவிவரத்தை திருத்து",
    updatePersonal:           "உங்கள் தனிப்பட்ட தகவலை புதுப்பிக்கவும்.",
    fullName:                 "முழு பெயர்",
    phoneNumber:              "தொலைபேசி எண்",
    department:               "துறை",
    designation:              "பதவி",
    address:                  "முகவரி",
    saveProfile:              "சுயவிவரம் சேமி",
    profileUpdated:           "சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!",
    changePassword:           "கடவுச்சொல் மாற்று",
    updatePassword:           "உங்கள் கணக்கு கடவுச்சொல்லை புதுப்பிக்கவும்.",
    currentPassword:          "தற்போதைய கடவுச்சொல்",
    newPassword:              "புதிய கடவுச்சொல்",
    confirmPassword:          "புதிய கடவுச்சொல்லை உறுதிப்படுத்து",
    updatePasswordBtn:        "கடவுச்சொல் புதுப்பி",
    updating:                 "புதுப்பிக்கிறது...",
    passwordChanged:          "கடவுச்சொல் வெற்றிகரமாக மாற்றப்பட்டது!",
    passwordMismatch:         "புதிய கடவுச்சொற்கள் பொருந்தவில்லை.",
    passwordTooShort:         "கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்.",
    networkError:             "நெட்வொர்க் பிழை. மீண்டும் முயற்சிக்கவும்.",
  },

  hi: {
    // ── Employee ──
    employeePortal:       "कर्मचारी पोर्टल",
    dashboard:            "डैशबोर्ड",
    leaveRequest:         "छुट्टी अनुरोध",
    attendanceCorrection: "उपस्थिति सुधार",
    reports:              "रिपोर्ट",
    settings:             "सेटिंग्स",
    logout:               "लॉग आउट",
    employee:             "कर्मचारी",
    // ── Admin ──
    adminPortal:          "एडमिन पोर्टल",
    staffDirectory:       "स्टाफ निर्देशिका",
    leaveApproval:        "छुट्टी अनुमोदन",
    attendanceApproval:   "उपस्थिति अनुमोदन",
    auditLogs:            "ऑडिट लॉग",
    // ── Settings ──
    appearance:               "दिखावट",
    chooseTheme:              "अपना पसंदीदा थीम चुनें।",
    light:                    "हल्का",
    dark:                     "गहरा",
    language:                 "भाषा",
    selectLanguage:           "अपनी पसंदीदा भाषा चुनें।",
    notificationPreferences:  "सूचना प्राथमिकताएं",
    manageNotifications:      "आप जो सूचनाएं प्राप्त करते हैं उन्हें प्रबंधित करें।",
    attendanceAlerts:         "उपस्थिति अलर्ट",
    attendanceAlertsDesc:     "दैनिक उपस्थिति स्थिति के बारे में सूचित हों",
    leaveUpdates:             "छुट्टी अनुरोध अपडेट",
    leaveUpdatesDesc:         "जब आपकी छुट्टी स्वीकृत या अस्वीकार हो",
    correctionStatus:         "सुधार अनुरोध स्थिति",
    correctionStatusDesc:     "आपके उपस्थिति सुधार अनुरोधों पर अपडेट",
    emailNotifications:       "ईमेल सूचनाएं",
    emailNotificationsDesc:   "ईमेल के माध्यम से सूचनाएं प्राप्त करें",
    editProfile:              "प्रोफ़ाइल संपादित करें",
    updatePersonal:           "अपनी व्यक्तिगत जानकारी अपडेट करें।",
    fullName:                 "पूरा नाम",
    phoneNumber:              "फ़ोन नंबर",
    department:               "विभाग",
    designation:              "पदनाम",
    address:                  "पता",
    saveProfile:              "प्रोफ़ाइल सहेजें",
    profileUpdated:           "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!",
    changePassword:           "पासवर्ड बदलें",
    updatePassword:           "अपना खाता पासवर्ड अपडेट करें।",
    currentPassword:          "वर्तमान पासवर्ड",
    newPassword:              "नया पासवर्ड",
    confirmPassword:          "नए पासवर्ड की पुष्टि करें",
    updatePasswordBtn:        "पासवर्ड अपडेट करें",
    updating:                 "अपडेट हो रहा है...",
    passwordChanged:          "पासवर्ड सफलतापूर्वक बदला गया!",
    passwordMismatch:         "नए पासवर्ड मेल नहीं खाते।",
    passwordTooShort:         "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    networkError:             "नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।",
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const t = translations[language];
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);